// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Selu383.SP25.Api;

#nullable disable

namespace Selu383.SP25.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250212041054_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Selu383.SP25.Api.Entities.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Slidell, LA",
                            Name = "The Grand Slidell Santikos",
                            SeatCount = 250
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hammond, LA",
                            Name = "AMC Hammond Palace 10",
                            SeatCount = 300
                        },
                        new
                        {
                            Id = 3,
                            Address = "Covington, LA",
                            Name = "Regal Covington Stadium 14",
                            SeatCount = 150
                        },
                        new
                        {
                            Id = 4,
                            Address = "Baton Rouge, LA",
                            Name = "AMC Mall of Louisiana 15",
                            SeatCount = 250
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
